services:
  db:
    container_name: postgresql
    build:
      context: .docker/postgres/
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - '.docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aplicativoTeste